name: nft_shopui
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  flutter:
    sdk: flutter
  google_fonts: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true